/**
 * Deterministic Workout source-identity for health-sync reconciliation.
 *
 * ENGINEERING ASSUMPTION — NOT SCIENTIFIC PARAMETER:
 * Identity uses exact source fields only (externalId, or type+startAt+endAt).
 * It must never use fuzzy time windows or calorie similarity.
 */

/** User-entered stepper rows are durable records, not members of a sync feed. */
export const MANUAL_STEPPER_SOURCE_PREFIX = "manual:stepper:";

export type WorkoutIdentitySource = {
  externalId?: string | null;
  type: string;
  startAt: string | Date;
  endAt: string | Date;
};

/** Synthetic IDs generated by older sync versions included a positional index. */
export function isLegacySyntheticWorkoutId(value: string | null | undefined): boolean {
  return typeof value === "string" && /^training-\d{4}-\d{2}-\d{2}-\d+-/.test(value.trim());
}

function toIsoInstant(value: string | Date): string {
  if (value instanceof Date) return value.toISOString();
  const parsed = new Date(value);
  if (!Number.isFinite(parsed.getTime())) {
    throw new Error(`invalid workout instant for source identity: ${value}`);
  }
  return parsed.toISOString();
}

/**
 * Stable identity key scoped per daily health row.
 * Prefer explicit externalId; otherwise fingerprint exact type + interval endpoints.
 */
export function workoutFingerprint(workout: Omit<WorkoutIdentitySource, "externalId">): string {
  return `fp:${workout.type}|${toIsoInstant(workout.startAt)}|${toIsoInstant(workout.endAt)}`;
}

export function workoutSourceIdentity(workout: WorkoutIdentitySource): string {
  const externalId = typeof workout.externalId === "string" ? workout.externalId.trim() : "";
  if (externalId.length > 0 && !isLegacySyntheticWorkoutId(externalId)) {
    return `ext:${externalId}`;
  }
  return workoutFingerprint(workout);
}
